name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: ${{ matrix.java }}
    - name: Build released widgets
      run: mvn clean verify -DskipTests --file pom.xml
    - name: Build incubating widgets
      run: mvn clean verify -Pincubation -DskipTests --file pom.xml
  
